---
- hosts: thoughtworks
  sudo: yes
  tasks:
    - name: install make
      apt: pkg=make state=installed update_cache=true
    - name: Installs git
      apt: pkg=git state=installed update_cache=true
    - name: clones git repo
      command: git clone https://github.com/iamrobs/infra-problem
    - name: installs JVM
      apt: pkg=openjdk-7-jre-headless state=installed update_cache=true
    - name: installs leiningen
      command: sudo curl https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein -o /usr/local/bin/lein
    - name: permissions for lein
      command: sudo chmod a+x /usr/local/bin/lein       
    - name: Installs supervisor
      apt: pkg=supervisor state=installed update_cache=true
      notify:
        - start supervisor
    - name: create application log file locations
      command: sudo mkdir -p /var/www/front-end/app/ /var/www/newsfeed/app/ /var/www/quotes/app/ /var/www/logs